env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - prettier
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
  react/jsx-newline:
    - warn
    - prevent: false
  react/react-in-jsx-scope:
    - 'off'
  prettier/prettier:
    - warn
ignorePatterns:
  - '*.cjs'
  - '*.test.tsx'
  - '*.test.ts'